### PR TITLE
fix: helm value file merge

### LINKED ISSUE #32: Helm failing on merging of values files
I encounter the following issue on release-2 when trying to render Helm charts, e.g. cert-manager in this case:

```
ytt: Error: Overlaying data values (in following order: myks-data.ytt.yaml, additional data values): 
One or more data values were invalid
====================================

Given data value is not declared in schema
cert-manager.yaml:
    |
  1 | installCRDs: true
    |

    = found: installCRDs
    = expected: one of { application, environment, helm, myks } (from data-schema.ytt.yaml:8)
```

This is the ytt log-line that precedes the failure:

```
Running command args=["--file=lib","--file=envs/data-schema.ytt.yaml","--file=.myks/tmp/myks-data.ytt.yaml","--data-values-file=envs/myks/_apps/cert-manager/.myks/tmp/helm/cert-manager.yaml","--data-values-inspect"] cmd=ytt
```

### PR DESCRIPTION
**Pull request by fritzduchardt**
Closes #32

### CODE REVIEW

**Comment by Zebradil** [comment]
Thanks Fritz!

Sorry, it was a busy end of the week, I'll take a look later today.

File: internal/myks/globe.go [hunk 1]
```diff
@@ -354,3 +354,7 @@ func (g *Globe) ytt(paths []string, args ...string) (CmdResult, error) {
 func (g *Globe) yttS(paths []string, stdin io.Reader, args ...string) (CmdResult, error) {
 	return runYttWithFilesAndStdin(append(g.extraYttPaths, paths...), stdin, args...)
 }
+
+func (g *Globe) mergeValuesYaml(valueFilesYaml string) (CmdResult, error) {
+	return runYttWithFilesAndStdin(nil, nil, "--data-values-file="+valueFilesYaml, "--data-values-inspect")
+}
```
Comment (Zebradil) [inline internal/myks/globe.go:360]: It doesn't make much sense to attach this function to the Globe struct, because the function is not using any data from the struct. I suggest moving this function into the `util.go` file (and adding a comment that it merges multiple yaml documents from a given file).

**Review by Zebradil — CHANGES_REQUESTED** [review]
Good catch, I didn't have a test case for this (but I added it: https://github.com/mykso/myks/commit/53e50ba2b9e7e0e598c43ce261b9ed34703bc9c7).

Check the comment, otherwise, LGTM.

File: internal/myks/globe.go (hunk 1 above)
Comment (fritzduchardt) [reply internal/myks/globe.go:360]: Good point - addressed!

@linusfr please review ;)

**Review by Zebradil — APPROVED** [review]
